name: CI Additional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doctests:
    name: Doctests
    runs-on: ubuntu-latest
    if: github.repository == 'xarray-contrib/pint-xarray'
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: initialize cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-py3.10-${{ hashFiles('ci/requirements/**.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-py3.10-
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: install dependencies
      run: |
        python -m pip install -r ci/requirements.txt
    - name: install pint-xarray
      run: |
        python -m pip install .
    - name: show versions
      run: |
        python -c 'import pint_xarray'
    - name: run doctests
      run: |
        python -m pytest --doctest-modules pint_xarray --ignore pint_xarray/tests
